export const GAME_CATEGORIES = [
  'animals',
  'sports',
  'gross out',
  'school',
  'magical',
  'silly fun',
  'superheroes',
  'jobs',
  'food fun',
  'vacations',
  'cool technology',
  'kids tv and movies'
] as const;

export type GameCategory = typeof GAME_CATEGORIES[number];

export const WORD_LISTS: Record<GameCategory, string[]> = {
  'animals': [
    'elephant', 'giraffe', 'penguin', 'kangaroo', 'butterfly', 'dolphin', 'tiger', 'panda',
    'monkey', 'zebra', 'lion', 'bear', 'rabbit', 'mouse', 'horse', 'dog', 'cat', 'bird',
    'fish', 'turtle', 'snake', 'lizard', 'frog', 'spider', 'ant', 'bee', 'cow', 'pig',
    'whale', 'shark', 'octopus', 'starfish', 'seahorse', 'jellyfish', 'crab', 'lobster',
    'shrimp', 'salmon', 'trout', 'bass', 'tuna', 'eagle', 'hawk', 'owl', 'robin', 'sparrow',
    'cardinal', 'bluejay', 'crow', 'raven', 'dove', 'swan', 'duck', 'goose', 'turkey', 'chicken',
    'rooster', 'peacock', 'flamingo', 'pelican', 'heron', 'stork', 'ostrich', 'emu', 'kiwi',
    'parrot', 'toucan', 'macaw', 'cockatoo', 'canary', 'finch', 'woodpecker', 'hummingbird',
    'vulture', 'condor', 'falcon', 'kestrel', 'buzzard', 'albatross', 'seagull', 'puffin',
    'cheetah', 'leopard', 'jaguar', 'lynx', 'bobcat', 'cougar', 'panther', 'ocelot',
    'wolf', 'fox', 'coyote', 'jackal', 'hyena', 'raccoon', 'skunk', 'badger', 'otter',
    'beaver', 'squirrel', 'chipmunk', 'groundhog', 'mole', 'hedgehog', 'porcupine', 'armadillo',
    'sloth', 'anteater', 'aardvark', 'platypus', 'echidna', 'koala', 'wombat', 'wallaby',
    'opossum', 'ferret', 'mink', 'weasel', 'stoat', 'ermine', 'marten', 'wolverine',
    'deer', 'elk', 'moose', 'caribou', 'reindeer', 'antelope', 'gazelle', 'impala',
    'buffalo', 'bison', 'yak', 'oxen', 'goat', 'sheep', 'lamb', 'llama', 'alpaca',
    'camel', 'dromedary', 'hippo', 'rhino', 'tapir', 'manatee', 'dugong', 'narwhal',
    'walrus', 'seal', 'sealion', 'orca', 'beluga', 'sperm', 'blue', 'gray', 'humpback',
    'python', 'cobra', 'viper', 'rattler', 'boa', 'anaconda', 'mamba', 'adder',
    'gecko', 'iguana', 'chameleon', 'monitor', 'skink', 'salamander', 'newt', 'tadpole',
    'toad', 'bullfrog', 'treefrog', 'poison', 'dart', 'axolotl', 'crocodile', 'alligator',
    'turtle', 'tortoise', 'terrapin', 'snapper', 'slider', 'box', 'sea', 'leatherback',
    'scorpion', 'tarantula', 'widow', 'recluse', 'centipede', 'millipede', 'tick', 'mite',
    'mosquito', 'fly', 'gnat', 'midge', 'wasp', 'hornet', 'yellowjacket', 'bumblebee',
    'honeybee', 'carpenter', 'leafcutter', 'mason', 'sweat', 'mining', 'cuckoo', 'orchid',
    'butterfly', 'monarch', 'swallowtail', 'admiral', 'painted', 'lady', 'fritillary', 'copper',
    'skipper', 'hairstreak', 'blue', 'sulfur', 'white', 'moth', 'luna', 'cecropia',
    'polyphemus', 'io', 'sphinx', 'hummingbird', 'clearwing', 'tiger', 'woolly', 'bear',
    'tent', 'caterpillar', 'inchworm', 'cutworm', 'armyworm', 'hornworm', 'webworm', 'bagworm',
    'beetle', 'ladybug', 'firefly', 'june', 'stag', 'rhinoceros', 'scarab', 'weevil',
    'borer', 'bark', 'click', 'ground', 'rove', 'soldier', 'blister', 'carrion',
    'cricket', 'grasshopper', 'katydid', 'locust', 'cicada', 'aphid', 'scale', 'mealybug',
    'whitefly', 'thrips', 'leafhopper', 'planthopper', 'psyllid', 'adelgid', 'woolly', 'aphid'
  ],
  'sports': [
    'football', 'basketball', 'baseball', 'soccer', 'tennis', 'swimming', 'hockey', 'golf',
    'volleyball', 'wrestling', 'boxing', 'cycling', 'running', 'jumping', 'skiing', 'skating',
    'surfing', 'bowling', 'archery', 'diving', 'karate', 'yoga', 'dancing', 'climbing',
    'badminton', 'cricket', 'rugby', 'polo', 'lacrosse', 'softball', 'handball', 'squash',
    'racquetball', 'pingpong', 'tabletennis', 'billiards', 'pool', 'snooker', 'darts', 'chess',
    'checkers', 'backgammon', 'scrabble', 'monopoly', 'poker', 'bridge', 'crossword', 'sudoku',
    'marathon', 'sprint', 'hurdles', 'relay', 'javelin', 'shotput', 'discus', 'hammer',
    'polevault', 'highjump', 'longjump', 'triplejump', 'decathlon', 'heptathlon', 'pentathlon', 'triathlon',
    'weightlifting', 'powerlifting', 'bodybuilding', 'crossfit', 'aerobics', 'pilates', 'zumba', 'spinning',
    'rowing', 'kayaking', 'canoeing', 'sailing', 'windsurfing', 'kitesurfing', 'wakeboarding', 'waterskiing',
    'snowboarding', 'sledding', 'bobsled', 'luge', 'skeleton', 'curling', 'biathlon', 'nordic',
    'alpine', 'freestyle', 'moguls', 'halfpipe', 'slopestyle', 'cross', 'country', 'downhill',
    'slalom', 'giant', 'super', 'combined', 'parallel', 'boardercross', 'skicross', 'aerials',
    'figureskating', 'speedskating', 'shorttrack', 'icedancing', 'pairs', 'singles', 'synchronized', 'ice',
    'fieldhockey', 'icehockey', 'roller', 'inline', 'street', 'bandy', 'floorball', 'broomball',
    'netball', 'korfball', 'dodgeball', 'kickball', 'wiffle', 'stickball', 'rounders', 'pesapallo',
    'futsal', 'beach', 'arena', 'gaelic', 'australian', 'canadian', 'american', 'association',
    'hurling', 'camogie', 'shinty', 'bandy', 'tchoukball', 'ultimate', 'frisbee', 'disc',
    'horseback', 'dressage', 'jumping', 'eventing', 'polo', 'rodeo', 'barrel', 'racing',
    'bronc', 'bull', 'riding', 'roping', 'cutting', 'reining', 'western', 'english',
    'motocross', 'supercross', 'enduro', 'trials', 'speedway', 'drag', 'nascar', 'formula',
    'rally', 'karting', 'autocross', 'hillclimb', 'drifting', 'touring', 'stock', 'open',
    'fencing', 'epee', 'foil', 'sabre', 'rapier', 'sword', 'blade', 'thrust',
    'judo', 'jujitsu', 'aikido', 'taekwondo', 'hapkido', 'kungfu', 'wushu', 'tai',
    'muay', 'thai', 'kickboxing', 'savate', 'capoeira', 'krav', 'maga', 'mixed',
    'martial', 'arts', 'grappling', 'submission', 'brazilian', 'jiujitsu', 'sambo', 'sumo',
    'rockclimbing', 'bouldering', 'mountaineering', 'rappelling', 'caving', 'spelunking', 'canyoning', 'via',
    'ferrata', 'alpine', 'aid', 'free', 'solo', 'trad', 'sport', 'indoor'
  ],
  'gross out': [
    'slime', 'booger', 'mud', 'worm', 'slug', 'spider', 'yucky', 'stinky', 'slimy', 'gooey',
    'messy', 'dirty', 'smelly', 'gross', 'icky', 'nasty', 'grimy', 'moldy', 'rotten', 'soggy',
    'gunk', 'grime', 'muck', 'crud', 'ooze', 'scum', 'filth', 'slop', 'sludge', 'gloop',
    'snot', 'phlegm', 'mucus', 'drool', 'slobber', 'spit', 'saliva', 'bile', 'pus', 'scab',
    'blister', 'pimple', 'zit', 'wart', 'fungus', 'mold', 'mildew', 'bacteria', 'germs', 'microbes',
    'garbage', 'trash', 'refuse', 'waste', 'rubbish', 'litter', 'debris', 'scraps', 'leftovers', 'spoiled',
    'putrid', 'rank', 'foul', 'fetid', 'musty', 'dank', 'sour', 'rancid', 'stale', 'funky',
    'sweat', 'perspiration', 'odor', 'stench', 'reek', 'funk', 'aroma', 'whiff', 'pong', 'smell',
    'maggot', 'larvae', 'grub', 'caterpillar', 'beetle', 'roach', 'cockroach', 'termite', 'louse', 'flea',
    'tick', 'mite', 'bed', 'bug', 'mosquito', 'gnat', 'fly', 'fruit', 'house', 'blow',
    'sewer', 'drain', 'toilet', 'bathroom', 'outhouse', 'porta', 'potty', 'cesspool', 'septic', 'manure',
    'dung', 'fertilizer', 'compost', 'decay', 'decompose', 'rot', 'putrefy', 'ferment', 'spoil', 'curdle',
    'vomit', 'puke', 'barf', 'hurl', 'spew', 'upchuck', 'ralph', 'toss', 'cookies', 'sick',
    'nausea', 'queasy', 'dizzy', 'woozy', 'green', 'gills', 'motion', 'sickness', 'car', 'sea',
    'burp', 'belch', 'hiccup', 'gas', 'fart', 'toot', 'flatulence', 'wind', 'pass', 'break',
    'earwax', 'cerumen', 'dirt', 'grit', 'sand', 'dust', 'lint', 'fuzz', 'hair', 'dandruff',
    'skin', 'flakes', 'scales', 'peeling', 'sunburn', 'blotchy', 'rash', 'hives', 'eczema', 'psoriasis',
    'pollen', 'allergens', 'sneeze', 'snot', 'runny', 'nose', 'congestion', 'stuffy', 'blocked', 'clogged',
    'tar', 'oil', 'grease', 'gum', 'sticky', 'tacky', 'adhesive', 'glue', 'paste', 'cement',
    'plaster', 'mortar', 'concrete', 'asphalt', 'pitch', 'resin', 'sap', 'latex', 'rubber', 'plastic'
  ],
  'school': [
    'teacher', 'student', 'classroom', 'homework', 'pencil', 'eraser', 'notebook', 'backpack',
    'lunch', 'recess', 'library', 'science', 'math', 'reading', 'writing', 'spelling', 'test',
    'grade', 'friend', 'playground', 'cafeteria', 'principal', 'desk', 'chair', 'book',
    'textbook', 'workbook', 'binder', 'folder', 'paper', 'pen', 'marker', 'crayon', 'chalk',
    'whiteboard', 'blackboard', 'smartboard', 'projector', 'computer', 'tablet', 'calculator', 'ruler', 'compass', 'protractor',
    'scissors', 'glue', 'tape', 'stapler', 'clips', 'pushpins', 'thumbtacks', 'bulletin', 'board', 'poster',
    'map', 'globe', 'dictionary', 'encyclopedia', 'atlas', 'almanac', 'thesaurus', 'reference', 'manual', 'guide',
    'curriculum', 'syllabus', 'lesson', 'plan', 'unit', 'chapter', 'section', 'page', 'paragraph', 'sentence',
    'word', 'letter', 'alphabet', 'phonics', 'grammar', 'vocabulary', 'comprehension', 'fluency', 'literacy', 'numeracy',
    'addition', 'subtraction', 'multiplication', 'division', 'fraction', 'decimal', 'percent', 'geometry', 'algebra', 'calculus',
    'biology', 'chemistry', 'physics', 'earth', 'space', 'astronomy', 'ecology', 'environment', 'weather', 'climate',
    'history', 'geography', 'civics', 'government', 'economics', 'sociology', 'psychology', 'philosophy', 'ethics', 'religion',
    'art', 'music', 'drama', 'theater', 'dance', 'physical', 'education', 'health', 'nutrition', 'safety',
    'foreign', 'language', 'spanish', 'french', 'german', 'italian', 'chinese', 'japanese', 'russian', 'latin',
    'kindergarten', 'elementary', 'middle', 'junior', 'high', 'senior', 'freshman', 'sophomore', 'junior', 'senior',
    'preschool', 'daycare', 'nursery', 'academy', 'institute', 'university', 'college', 'campus', 'dormitory', 'residence',
    'hallway', 'corridor', 'locker', 'combination', 'lock', 'key', 'card', 'badge', 'uniform', 'dress',
    'code', 'policy', 'rules', 'regulations', 'discipline', 'detention', 'suspension', 'expulsion', 'tardy', 'absent',
    'present', 'attendance', 'roll', 'call', 'register', 'roster', 'list', 'schedule', 'timetable', 'calendar',
    'semester', 'quarter', 'trimester', 'year', 'summer', 'winter', 'spring', 'fall', 'break', 'vacation',
    'report', 'card', 'transcript', 'diploma', 'certificate', 'award', 'honor', 'merit', 'distinction', 'achievement',
    'scholarship', 'grant', 'loan', 'tuition', 'fee', 'cost', 'budget', 'financial', 'aid', 'assistance',
    'club', 'activity', 'sport', 'team', 'band', 'choir', 'orchestra', 'drama', 'debate', 'chess',
    'student', 'council', 'government', 'election', 'vote', 'campaign', 'candidate', 'office', 'president', 'vice',
    'secretary', 'treasurer', 'representative', 'delegate', 'committee', 'meeting', 'assembly', 'rally', 'spirit', 'week'
  ],
  'magical': [
    'wizard', 'fairy', 'magic', 'wand', 'spell', 'potion', 'castle', 'dragon', 'unicorn',
    'princess', 'prince', 'knight', 'treasure', 'crystal', 'enchanted', 'mystical', 'fantasy',
    'sorcerer', 'witch', 'cauldron', 'phoenix', 'pegasus', 'mermaid', 'genie', 'rainbow',
    'warlock', 'shaman', 'druid', 'necromancer', 'alchemist', 'mage', 'sage', 'oracle', 'prophet', 'seer',
    'enchantress', 'sorceress', 'priestess', 'goddess', 'nymph', 'sprite', 'pixie', 'elf', 'dwarf', 'gnome',
    'hobbit', 'goblin', 'orc', 'troll', 'giant', 'ogre', 'demon', 'devil', 'angel', 'seraph',
    'cherub', 'archangel', 'guardian', 'spirit', 'ghost', 'phantom', 'specter', 'wraith', 'banshee', 'poltergeist',
    'vampire', 'werewolf', 'shapeshifter', 'metamorph', 'changeling', 'doppelganger', 'mimic', 'illusion', 'apparition', 'vision',
    'griffin', 'hippogriff', 'centaur', 'minotaur', 'sphinx', 'chimera', 'hydra', 'kraken', 'leviathan', 'behemoth',
    'basilisk', 'cockatrice', 'wyvern', 'drake', 'wyrm', 'salamander', 'phoenix', 'firebird', 'thunderbird', 'roc',
    'pegasus', 'hippocamp', 'kelpie', 'selkie', 'siren', 'harpy', 'banshee', 'valkyrie', 'amazon', 'warrior',
    'paladin', 'crusader', 'templar', 'champion', 'hero', 'heroine', 'adventurer', 'explorer', 'quest', 'journey',
    'mission', 'destiny', 'fate', 'prophecy', 'legend', 'myth', 'folklore', 'tale', 'story', 'epic',
    'saga', 'chronicle', 'ballad', 'song', 'chant', 'incantation', 'invocation', 'summoning', 'ritual', 'ceremony',
    'amulet', 'talisman', 'charm', 'pendant', 'medallion', 'locket', 'ring', 'crown', 'tiara', 'circlet',
    'scepter', 'staff', 'rod', 'orb', 'sphere', 'globe', 'crystal', 'ball', 'mirror', 'scrying',
    'divination', 'augury', 'omen', 'portent', 'sign', 'symbol', 'rune', 'glyph', 'sigil', 'seal',
    'scroll', 'tome', 'grimoire', 'spellbook', 'manual', 'codex', 'manuscript', 'parchment', 'papyrus', 'vellum',
    'elixir', 'philter', 'tonic', 'brew', 'concoction', 'mixture', 'formula', 'recipe', 'ingredient', 'component',
    'herb', 'flower', 'root', 'bark', 'leaf', 'seed', 'berry', 'fruit', 'mushroom', 'fungus',
    'tower', 'spire', 'dungeon', 'chamber', 'hall', 'throne', 'room', 'laboratory', 'workshop', 'forge',
    'altar', 'shrine', 'temple', 'monastery', 'abbey', 'cathedral', 'church', 'chapel', 'sanctuary', 'haven',
    'realm', 'kingdom', 'empire', 'domain', 'territory', 'land', 'world', 'dimension', 'plane', 'universe',
    'cosmos', 'void', 'abyss', 'netherworld', 'underworld', 'afterlife', 'heaven', 'paradise', 'elysium', 'nirvana',
    'portal', 'gateway', 'doorway', 'passage', 'bridge', 'tunnel', 'vortex', 'rift', 'tear', 'fissure'
  ],
  'silly fun': [
    'giggle', 'laugh', 'funny', 'joke', 'silly', 'goofy', 'crazy', 'wacky', 'hilarious',
    'amusing', 'tickle', 'smile', 'happy', 'cheerful', 'playful', 'bouncy', 'wiggly',
    'jiggly', 'bubbly', 'peppy', 'zippy', 'snappy', 'perky', 'quirky', 'zany',
    'nutty', 'loony', 'batty', 'bonkers', 'kooky', 'daffy', 'dippy', 'dotty', 'screwy', 'wacko',
    'whimsical', 'absurd', 'ridiculous', 'preposterous', 'outrageous', 'bizarre', 'odd', 'weird', 'strange', 'peculiar',
    'comical', 'droll', 'witty', 'clever', 'humorous', 'jovial', 'jolly', 'merry', 'gleeful', 'joyful',
    'elated', 'ecstatic', 'euphoric', 'exuberant', 'jubilant', 'thrilled', 'delighted', 'overjoyed', 'blissful', 'radiant',
    'giggly', 'chuckling', 'snickering', 'grinning', 'beaming', 'smirking', 'cackling', 'roaring', 'howling', 'shrieking',
    'chortling', 'tittering', 'snorting', 'belly', 'splitting', 'sides', 'ribs', 'tickled', 'pink', 'punch',
    'drunk', 'giddy', 'dizzy', 'lightheaded', 'whoozy', 'tipsy', 'punch', 'drunk', 'slaphappy', 'loopy',
    'bonkers', 'bananas', 'nuts', 'crackers', 'potty', 'barmy', 'daft', 'balmy', 'touched', 'unhinged',
    'clown', 'jester', 'comedian', 'comic', 'joker', 'prankster', 'trickster', 'buffoon', 'fool', 'court',
    'circus', 'carnival', 'fair', 'funhouse', 'amusement', 'park', 'roller', 'coaster', 'ferris', 'wheel',
    'merry', 'round', 'carousel', 'bumper', 'cars', 'cotton', 'candy', 'popcorn', 'balloon', 'confetti',
    'streamers', 'party', 'celebration', 'festival', 'fiesta', 'gala', 'bash', 'shindig', 'hootenanny', 'jamboree',
    'rumpus', 'hullabaloo', 'brouhaha', 'hubbub', 'commotion', 'fracas', 'kerfuffle', 'to', 'brouhaha', 'ballyhoo',
    'hoopla', 'fanfare', 'spectacle', 'extravaganza', 'pageant', 'parade', 'procession', 'march', 'rally', 'gathering',
    'assembly', 'congregation', 'convention', 'conference', 'summit', 'meeting', 'reunion', 'get', 'together', 'pow',
    'wow', 'huddle', 'session', 'workshop', 'seminar', 'symposium', 'colloquium', 'forum', 'panel', 'discussion',
    'whoopee', 'cushion', 'buzzer', 'squirter', 'fake', 'mustache', 'glasses', 'nose', 'bow', 'tie',
    'polka', 'dot', 'stripes', 'plaid', 'checkered', 'rainbow', 'multicolored', 'bright', 'vivid', 'neon',
    'fluorescent', 'glowing', 'sparkling', 'glittering', 'shimmering', 'twinkling', 'dazzling', 'brilliant', 'radiant', 'luminous',
    'squeaky', 'toy', 'rubber', 'duck', 'chicken', 'hammer', 'horn', 'whistle', 'kazoo', 'noisemaker',
    'rattle', 'bell', 'chime', 'ding', 'dong', 'ping', 'pong', 'boing', 'sproing', 'bonk',
    'thud', 'plop', 'splat', 'squish', 'squelch', 'splish', 'splash', 'whoosh', 'zoom', 'zip'
  ],
  'superheroes': [
    'hero', 'power', 'cape', 'mask', 'strength', 'flying', 'rescue', 'brave', 'courage',
    'justice', 'villain', 'battle', 'protect', 'save', 'mission', 'secret', 'identity',
    'costume', 'super', 'amazing', 'incredible', 'mighty', 'ultimate', 'fantastic',
    'superhuman', 'extraordinary', 'phenomenal', 'remarkable', 'outstanding', 'exceptional', 'marvelous', 'wonderful', 'spectacular', 'magnificent',
    'invincible', 'indestructible', 'invulnerable', 'unstoppable', 'unbeatable', 'unconquerable', 'undefeatable', 'impenetrable', 'impervious', 'immune',
    'telepathy', 'telekinesis', 'teleportation', 'invisibility', 'intangibility', 'shapeshifting', 'regeneration', 'immortality', 'precognition', 'clairvoyance',
    'superhearing', 'supervision', 'infrared', 'thermal', 'xray', 'laser', 'freeze', 'heat', 'fire', 'ice',
    'lightning', 'thunder', 'storm', 'weather', 'control', 'manipulation', 'elemental', 'earth', 'water', 'air',
    'magnetic', 'gravity', 'time', 'space', 'dimensional', 'portal', 'energy', 'plasma', 'radiation', 'atomic',
    'molecular', 'cellular', 'genetic', 'mutation', 'evolution', 'adaptation', 'transformation', 'metamorphosis', 'enhancement', 'augmentation',
    'cybernetic', 'bionic', 'robotic', 'mechanical', 'technological', 'futuristic', 'advanced', 'sophisticated', 'cutting', 'edge',
    'headquarters', 'base', 'lair', 'hideout', 'fortress', 'tower', 'cave', 'underground', 'laboratory', 'workshop',
    'gadget', 'device', 'tool', 'weapon', 'armor', 'suit', 'utility', 'belt', 'grappling', 'hook',
    'shield', 'sword', 'staff', 'hammer', 'bow', 'arrow', 'boomerang', 'throwing', 'star', 'explosive',
    'vehicle', 'motorcycle', 'car', 'plane', 'helicopter', 'submarine', 'spaceship', 'hovercraft', 'jetpack', 'rocket',
    'boots', 'gloves', 'helmet', 'goggles', 'visor', 'communicator', 'tracker', 'scanner', 'detector', 'analyzer',
    'sidekick', 'partner', 'ally', 'teammate', 'squad', 'league', 'alliance', 'federation', 'organization', 'agency',
    'mentor', 'trainer', 'guide', 'teacher', 'master', 'sensei', 'guru', 'sage', 'wise', 'elder',
    'nemesis', 'archenemy', 'adversary', 'foe', 'rival', 'opponent', 'antagonist', 'criminal', 'mastermind', 'overlord',
    'henchman', 'minion', 'lackey', 'thug', 'goon', 'assassin', 'mercenary', 'bounty', 'hunter', 'spy',
    'citizen', 'civilian', 'bystander', 'witness', 'victim', 'hostage', 'captive', 'prisoner', 'survivor', 'refugee',
    'comic', 'graphic', 'novel', 'series', 'issue', 'volume', 'chapter', 'panel', 'frame', 'bubble',
    'speech', 'thought', 'caption', 'narration', 'dialogue', 'monologue', 'exposition', 'backstory', 'origin', 'flashback',
    'cliffhanger', 'plot', 'twist', 'reveal', 'surprise', 'shocking', 'dramatic', 'climax', 'resolution', 'conclusion'
  ],
  'jobs': [
    'doctor', 'teacher', 'firefighter', 'police', 'nurse', 'pilot', 'chef', 'farmer',
    'builder', 'artist', 'singer', 'dancer', 'writer', 'scientist', 'engineer', 'mechanic',
    'dentist', 'veterinarian', 'librarian', 'mailman', 'baker', 'musician', 'actor', 'coach',
    'surgeon', 'physician', 'specialist', 'cardiologist', 'neurologist', 'pediatrician', 'psychiatrist', 'therapist', 'counselor', 'psychologist',
    'pharmacist', 'technician', 'paramedic', 'emergency', 'medical', 'responder', 'radiologist', 'anesthesiologist', 'pathologist', 'oncologist',
    'professor', 'instructor', 'educator', 'tutor', 'principal', 'superintendent', 'guidance', 'counselor', 'aide', 'substitute',
    'captain', 'lieutenant', 'sergeant', 'detective', 'investigator', 'officer', 'patrol', 'traffic', 'security', 'guard',
    'astronaut', 'aviation', 'controller', 'flight', 'attendant', 'navigator', 'copilot', 'helicopter', 'drone', 'operator',
    'pastry', 'sous', 'executive', 'line', 'cook', 'prep', 'server', 'waiter', 'waitress', 'bartender',
    'rancher', 'agricultural', 'worker', 'harvester', 'greenhouse', 'operator', 'livestock', 'manager', 'crop', 'inspector',
    'carpenter', 'electrician', 'plumber', 'roofer', 'mason', 'welder', 'painter', 'decorator', 'contractor', 'foreman',
    'sculptor', 'painter', 'illustrator', 'graphic', 'designer', 'photographer', 'filmmaker', 'animator', 'cartoonist', 'architect',
    'composer', 'conductor', 'pianist', 'guitarist', 'violinist', 'drummer', 'vocalist', 'songwriter', 'producer', 'sound',
    'director', 'producer', 'screenwriter', 'cinematographer', 'editor', 'makeup', 'costume', 'designer', 'stunt', 'double',
    'trainer', 'fitness', 'personal', 'sports', 'referee', 'umpire', 'commentator', 'broadcaster', 'journalist', 'reporter',
    'accountant', 'bookkeeper', 'financial', 'advisor', 'banker', 'teller', 'loan', 'officer', 'investment', 'analyst',
    'lawyer', 'attorney', 'judge', 'paralegal', 'court', 'clerk', 'bailiff', 'stenographer', 'mediator', 'arbitrator',
    'programmer', 'developer', 'analyst', 'technician', 'administrator', 'database', 'network', 'cybersecurity', 'specialist', 'consultant',
    'salesperson', 'representative', 'manager', 'supervisor', 'executive', 'director', 'president', 'chairman', 'owner', 'entrepreneur',
    'custodian', 'janitor', 'housekeeper', 'maintenance', 'worker', 'landscaper', 'groundskeeper', 'gardener', 'florist', 'decorator',
    'hairstylist', 'barber', 'beautician', 'manicurist', 'massage', 'therapist', 'personal', 'shopper', 'fashion', 'stylist',
    'social', 'worker', 'case', 'manager', 'volunteer', 'coordinator', 'fundraiser', 'nonprofit', 'administrator', 'community',
    'organizer', 'activist', 'advocate', 'lobbyist', 'politician', 'mayor', 'governor', 'senator', 'representative', 'diplomat',
    'translator', 'interpreter', 'language', 'specialist', 'foreign', 'correspondent', 'travel', 'agent', 'tour', 'guide'
  ],
  'food fun': [
    'pizza', 'hamburger', 'hotdog', 'sandwich', 'cookie', 'cake', 'candy', 'chocolate',
    'icecream', 'apple', 'banana', 'orange', 'grape', 'strawberry', 'watermelon', 'cheese',
    'bread', 'milk', 'juice', 'soda', 'popcorn', 'pretzel', 'donut', 'pancake', 'waffle',
    'spaghetti', 'lasagna', 'ravioli', 'macaroni', 'linguine', 'fettuccine', 'penne', 'rigatoni', 'tortellini', 'gnocchi',
    'burrito', 'taco', 'quesadilla', 'enchilada', 'nachos', 'salsa', 'guacamole', 'jalapeno', 'cilantro', 'lime',
    'sushi', 'ramen', 'noodles', 'tempura', 'teriyaki', 'wasabi', 'ginger', 'soy', 'sauce', 'rice',
    'curry', 'tikka', 'masala', 'naan', 'chapati', 'samosa', 'chutney', 'cardamom', 'turmeric', 'coriander',
    'croissant', 'baguette', 'danish', 'muffin', 'scone', 'bagel', 'toast', 'jam', 'jelly', 'marmalade',
    'honey', 'syrup', 'maple', 'butter', 'cream', 'yogurt', 'pudding', 'custard', 'mousse', 'souffle',
    'brownie', 'cupcake', 'frosting', 'icing', 'sprinkles', 'cherry', 'whipped', 'cream', 'caramel', 'fudge',
    'gummy', 'bears', 'lollipop', 'peppermint', 'licorice', 'taffy', 'marshmallow', 'jellybean', 'cotton', 'candy',
    'pineapple', 'mango', 'kiwi', 'papaya', 'coconut', 'avocado', 'blueberry', 'raspberry', 'blackberry', 'cranberry',
    'peach', 'pear', 'plum', 'apricot', 'cherry', 'lemon', 'lime', 'grapefruit', 'tangerine', 'mandarin',
    'carrot', 'broccoli', 'cauliflower', 'spinach', 'lettuce', 'cucumber', 'tomato', 'pepper', 'onion', 'garlic',
    'potato', 'sweet', 'corn', 'peas', 'beans', 'celery', 'mushroom', 'zucchini', 'eggplant', 'squash',
    'chicken', 'beef', 'pork', 'turkey', 'fish', 'salmon', 'tuna', 'shrimp', 'lobster', 'crab',
    'eggs', 'bacon', 'sausage', 'ham', 'deli', 'meat', 'pepperoni', 'salami', 'pastrami', 'roast',
    'soup', 'stew', 'chili', 'broth', 'bisque', 'chowder', 'minestrone', 'gazpacho', 'consomme', 'ramen',
    'salad', 'coleslaw', 'potato', 'macaroni', 'caesar', 'greek', 'cobb', 'waldorf', 'caprese', 'antipasto',
    'smoothie', 'milkshake', 'lemonade', 'iced', 'tea', 'coffee', 'espresso', 'cappuccino', 'latte', 'mocha',
    'water', 'sparkling', 'energy', 'drink', 'sports', 'vitamin', 'protein', 'shake', 'herbal', 'tea',
    'cereal', 'oatmeal', 'granola', 'muesli', 'bran', 'flakes', 'cheerios', 'cornflakes', 'rice', 'krispies',
    'trail', 'mix', 'nuts', 'almonds', 'peanuts', 'cashews', 'walnuts', 'pecans', 'pistachios', 'hazelnuts',
    'chips', 'crackers', 'cookies', 'pretzels', 'popcorn', 'peanut', 'butter', 'sunflower', 'seeds', 'raisins'
  ],
  'vacations': [
    'beach', 'ocean', 'mountain', 'camping', 'hotel', 'airplane', 'suitcase', 'camera',
    'sunglasses', 'vacation', 'holiday', 'travel', 'adventure', 'explore', 'discover',
    'island', 'forest', 'lake', 'river', 'park', 'zoo', 'museum', 'castle', 'monument',
    'resort', 'lodge', 'cabin', 'cottage', 'villa', 'chalet', 'hostel', 'motel', 'inn', 'bed',
    'breakfast', 'cruise', 'ship', 'yacht', 'sailboat', 'catamaran', 'ferry', 'submarine', 'houseboat', 'raft',
    'train', 'subway', 'metro', 'trolley', 'bus', 'coach', 'taxi', 'uber', 'rental', 'car',
    'motorcycle', 'bicycle', 'scooter', 'skateboard', 'rollerblades', 'walking', 'hiking', 'trekking', 'backpacking', 'climbing',
    'passport', 'visa', 'ticket', 'boarding', 'pass', 'luggage', 'backpack', 'duffel', 'bag', 'carry',
    'sunscreen', 'sunhat', 'swimsuit', 'bikini', 'trunks', 'flip', 'flops', 'sandals', 'snorkel', 'mask',
    'fins', 'scuba', 'diving', 'surfboard', 'boogie', 'board', 'kayak', 'canoe', 'paddle', 'boat',
    'tent', 'sleeping', 'flashlight', 'lantern', 'compass', 'map', 'gps', 'binoculars', 'fishing', 'rod',
    'campfire', 'marshmallows', 'smores', 'hotdogs', 'barbecue', 'grill', 'cooler', 'thermos', 'water', 'bottle',
    'guidebook', 'brochure', 'postcard', 'souvenir', 'gift', 'shop', 'memento', 'keepsake', 'photo', 'album',
    'selfie', 'panorama', 'landscape', 'sunset', 'sunrise', 'wildlife', 'nature', 'scenery', 'vista', 'overlook',
    'tropical', 'paradise', 'exotic', 'remote', 'pristine', 'unspoiled', 'breathtaking', 'spectacular', 'magnificent', 'stunning',
    'relaxation', 'rejuvenation', 'recreation', 'leisure', 'entertainment', 'activities', 'excursions', 'tours', 'sightseeing', 'attractions',
    'culture', 'heritage', 'tradition', 'customs', 'cuisine', 'local', 'authentic', 'indigenous', 'native', 'folklore',
    'language', 'dialect', 'accent', 'communication', 'translation', 'interpreter', 'guide', 'concierge', 'receptionist', 'staff',
    'itinerary', 'schedule', 'agenda', 'reservation', 'booking', 'confirmation', 'check', 'checkout', 'departure', 'arrival',
    'weather', 'climate', 'temperature', 'humidity', 'rainfall', 'sunshine', 'cloudy', 'clear', 'windy', 'calm',
    'seasons', 'summer', 'winter', 'spring', 'autumn', 'fall', 'peak', 'season', 'shoulder', 'low',
    'budget', 'expensive', 'affordable', 'cheap', 'luxury', 'economy', 'first', 'class', 'business', 'premium',
    'memories', 'experiences', 'stories', 'adventures', 'journeys', 'destinations', 'wanderlust', 'exploration', 'discovery', 'freedom'
  ],
  'cool technology': [
    'computer', 'robot', 'rocket', 'spaceship', 'satellite', 'laser', 'hologram', 'gadget',
    'invention', 'machine', 'device', 'future', 'digital', 'virtual', 'cyber', 'nano',
    'solar', 'electric', 'wireless', 'remote', 'smartphone', 'tablet', 'video', 'gaming',
    'artificial', 'intelligence', 'machine', 'learning', 'neural', 'network', 'algorithm', 'automation', 'programming', 'software',
    'hardware', 'processor', 'chip', 'microchip', 'circuit', 'motherboard', 'memory', 'storage', 'hard', 'drive',
    'monitor', 'screen', 'display', 'keyboard', 'mouse', 'touchpad', 'trackball', 'joystick', 'controller', 'headset',
    'virtual', 'reality', 'augmented', 'mixed', 'immersive', 'simulation', 'three', 'dimensional', 'graphics', 'animation',
    'internet', 'website', 'browser', 'search', 'engine', 'social', 'media', 'networking', 'streaming', 'download',
    'upload', 'cloud', 'computing', 'server', 'database', 'backup', 'security', 'encryption', 'firewall', 'antivirus',
    'bluetooth', 'wifi', 'ethernet', 'fiber', 'optic', 'broadband', 'bandwidth', 'connectivity', 'network', 'protocol',
    'drone', 'quadcopter', 'helicopter', 'autonomous', 'self', 'driving', 'electric', 'vehicle', 'hybrid', 'tesla',
    'battery', 'charger', 'power', 'bank', 'adapter', 'cable', 'cord', 'plug', 'outlet', 'generator',
    'renewable', 'energy', 'wind', 'turbine', 'hydroelectric', 'geothermal', 'biomass', 'nuclear', 'fusion', 'fission',
    'space', 'exploration', 'mars', 'rover', 'telescope', 'hubble', 'james', 'webb', 'international', 'station',
    'astronaut', 'cosmonaut', 'mission', 'launch', 'orbit', 'gravity', 'zero', 'weightless', 'atmosphere', 'vacuum',
    'biotechnology', 'genetics', 'dna', 'gene', 'therapy', 'cloning', 'stem', 'cell', 'crispr', 'genome',
    'medical', 'scanner', 'mri', 'xray', 'ultrasound', 'ct', 'scan', 'pacemaker', 'prosthetic', 'implant',
    'three', 'printer', 'additive', 'manufacturing', 'prototype', 'rapid', 'production', 'material', 'plastic', 'metal',
    'quantum', 'computing', 'supercomputer', 'parallel', 'processing', 'bit', 'qubit', 'entanglement', 'superposition', 'interference',
    'cryptocurrency', 'bitcoin', 'blockchain', 'digital', 'currency', 'wallet', 'mining', 'ledger', 'transaction', 'decentralized',
    'smartphone', 'iphone', 'android', 'apps', 'application', 'touchscreen', 'fingerprint', 'face', 'recognition', 'voice',
    'assistant', 'alexa', 'siri', 'google', 'smart', 'home', 'automation', 'thermostat', 'security', 'camera',
    'wearable', 'smartwatch', 'fitness', 'tracker', 'heart', 'rate', 'steps', 'calories', 'sleep', 'monitoring',
    'innovation', 'breakthrough', 'cutting', 'edge', 'state', 'art', 'revolutionary', 'disruptive', 'emerging', 'trending'
  ],
  'kids tv and movies': [
    'cartoon', 'animation', 'movie', 'character', 'adventure', 'comedy', 'family', 'fun',
    'story', 'hero', 'villain', 'friendship', 'team', 'quest', 'journey', 'magical',
    'fantasy', 'action', 'mystery', 'detective', 'treasure', 'discovery', 'rescue', 'brave',
    'disney', 'pixar', 'dreamworks', 'nickelodeon', 'cartoon', 'network', 'pbs', 'kids', 'netflix', 'streaming',
    'princess', 'prince', 'castle', 'kingdom', 'fairy', 'tale', 'once', 'upon', 'time', 'happily',
    'ever', 'after', 'magic', 'spell', 'witch', 'wizard', 'dragon', 'unicorn', 'talking', 'animals',
    'superhero', 'powers', 'cape', 'mask', 'costume', 'saving', 'world', 'good', 'versus', 'evil',
    'school', 'classroom', 'teacher', 'students', 'homework', 'field', 'trip', 'science', 'project', 'talent',
    'show', 'competition', 'contest', 'winning', 'losing', 'teamwork', 'cooperation', 'helping', 'sharing', 'caring',
    'family', 'siblings', 'parents', 'grandparents', 'pets', 'house', 'neighborhood', 'community', 'neighbors', 'friends',
    'playground', 'park', 'beach', 'forest', 'mountains', 'space', 'underwater', 'jungle', 'desert', 'arctic',
    'robots', 'aliens', 'monsters', 'dinosaurs', 'pirates', 'knights', 'cowboys', 'ninjas', 'detectives', 'explorers',
    'singing', 'dancing', 'music', 'songs', 'instruments', 'band', 'concert', 'performance', 'talent', 'show',
    'sports', 'games', 'playground', 'recess', 'summer', 'camp', 'vacation', 'holidays', 'birthday', 'party',
    'christmas', 'halloween', 'thanksgiving', 'easter', 'new', 'year', 'valentines', 'day', 'mothers', 'fathers',
    'learning', 'education', 'numbers', 'letters', 'reading', 'writing', 'counting', 'colors', 'shapes', 'sizes',
    'feelings', 'emotions', 'happy', 'sad', 'angry', 'scared', 'excited', 'surprised', 'proud', 'disappointed',
    'manners', 'please', 'thank', 'you', 'sorry', 'excuse', 'me', 'polite', 'respectful', 'kind',
    'imagination', 'creativity', 'pretend', 'play', 'make', 'believe', 'dress', 'up', 'costumes', 'roleplay',
    'toys', 'dolls', 'action', 'figures', 'blocks', 'puzzles', 'games', 'board', 'video', 'outdoor',
    'bedtime', 'stories', 'lullabies', 'dreams', 'nightmares', 'monsters', 'under', 'bed', 'dark', 'light',
    'growing', 'up', 'getting', 'older', 'responsibilities', 'chores', 'allowance', 'money', 'saving', 'spending',
    'environment', 'nature', 'recycling', 'conservation', 'earth', 'day', 'pollution', 'clean', 'green', 'eco',
    'diversity', 'differences', 'cultures', 'languages', 'traditions', 'acceptance', 'inclusion', 'understanding', 'tolerance', 'respect'
  ]
};

// Bonus words for each category - these are hidden in the puzzle but not in the word bank
export const BONUS_WORDS: Record<GameCategory, string[]> = {
  'animals': ['ecosystem', 'habitat', 'species', 'mammal', 'reptile', 'amphibian', 'invertebrate', 'vertebrate', 'predator', 'prey'],
  'sports': ['athlete', 'competition', 'tournament', 'championship', 'victory', 'defeat', 'strategy', 'technique', 'training', 'practice'],
  'gross out': ['disgusting', 'revolting', 'repulsive', 'nauseating', 'vile', 'loathsome', 'abhorrent', 'detestable', 'offensive', 'horrid'],
  'school': ['education', 'knowledge', 'learning', 'studying', 'graduation', 'academic', 'scholarship', 'curriculum', 'assignment', 'examination'],
  'magical': ['supernatural', 'otherworldly', 'paranormal', 'mystical', 'ethereal', 'spiritual', 'divine', 'celestial', 'transcendent', 'miraculous'],
  'silly fun': ['entertainment', 'amusement', 'recreation', 'merriment', 'festivity', 'celebration', 'enjoyment', 'pleasure', 'delight', 'happiness'],
  'superheroes': ['extraordinary', 'phenomenal', 'remarkable', 'spectacular', 'magnificent', 'invincible', 'legendary', 'epic', 'heroic', 'valiant'],
  'jobs': ['profession', 'occupation', 'career', 'employment', 'vocation', 'expertise', 'specialist', 'professional', 'workforce', 'industry'],
  'food fun': ['delicious', 'nutritious', 'appetizing', 'scrumptious', 'flavorful', 'tasty', 'savory', 'cuisine', 'recipe', 'ingredient'],
  'vacations': ['destination', 'excursion', 'expedition', 'getaway', 'retreat', 'journey', 'voyage', 'adventure', 'exploration', 'relaxation'],
  'cool technology': ['innovation', 'advancement', 'breakthrough', 'discovery', 'invention', 'development', 'progress', 'evolution', 'revolution', 'futuristic'],
  'kids tv and movies': ['entertainment', 'storytelling', 'animation', 'characters', 'adventure', 'imagination', 'creativity', 'inspiration', 'education', 'childhood']
};

export const WORD_SEARCH_CATEGORIES = ['random', ...[...GAME_CATEGORIES].sort()] as const;
export type WordSearchCategory = typeof WORD_SEARCH_CATEGORIES[number];

export const WORD_LISTS_WITH_BONUS = GAME_CATEGORIES.reduce((acc, category) => {
  acc[category] = [...WORD_LISTS[category], ...BONUS_WORDS[category]];
  return acc;
}, {} as Record<GameCategory, string[]>);

export const WOULD_YOU_RATHER_SCENARIOS: Record<GameCategory, string[]> = {
  'animals': [
    'Would you rather be able to talk to animals or be invisible to them?',
    'Would you rather have a pet dragon or a pet unicorn?',
    'Would you rather swim with dolphins or fly with eagles?',
    'Would you rather be as strong as an elephant or as fast as a cheetah?',
    'Would you rather have a house full of puppies or kittens?'
  ],
  'sports': [
    'Would you rather be the best basketball player or the best soccer player?',
    'Would you rather win an Olympic gold medal or be on your favorite sports team?',
    'Would you rather be able to throw a football 100 yards or hit a baseball 500 feet?',
    'Would you rather be super fast or super strong in sports?',
    'Would you rather play your favorite sport year-round or try a new sport every month?'
  ],
  'gross out': [
    'Would you rather step in a puddle of slime or find a worm in your apple?',
    'Would you rather have to clean up after a messy pet or a messy little sibling?',
    'Would you rather eat food that looks gross but tastes great or looks great but tastes gross?',
    'Would you rather have to pick up trash for a day or clean dirty bathrooms for an hour?',
    'Would you rather have sticky hands for a week or smelly feet for a month?'
  ],
  'school': [
    'Would you rather have no homework for a year or no tests for a year?',
    'Would you rather be the smartest kid in school or the most popular?',
    'Would you rather have a longer summer vacation or longer winter break?',
    'Would you rather always sit in the front row or always sit in the back row?',
    'Would you rather have school start later or end earlier?'
  ],
  'magical': [
    'Would you rather have a magic wand or a magic carpet?',
    'Would you rather be able to cast spells or brew potions?',
    'Would you rather live in a castle or a treehouse?',
    'Would you rather have a fairy godmother or a wise wizard mentor?',
    'Would you rather be able to turn invisible or read minds?'
  ],
  'silly fun': [
    'Would you rather have a silly walk or a silly laugh that you can\'t control?',
    'Would you rather wear clown shoes everywhere or a clown nose everywhere?',
    'Would you rather only be able to speak in rhymes or only be able to sing what you say?',
    'Would you rather have rainbow colored hair or glitter skin?',
    'Would you rather laugh like a hyena or snort when you laugh?'
  ],
  'superheroes': [
    'Would you rather be able to fly or be super strong?',
    'Would you rather have X-ray vision or super hearing?',
    'Would you rather wear a cape or a mask?',
    'Would you rather be able to become invisible or read minds?',
    'Would you rather save people from burning buildings or stop bank robbers?'
  ],
  'jobs': [
    'Would you rather be a doctor who helps people or a chef who makes delicious food?',
    'Would you rather be a teacher or a firefighter?',
    'Would you rather be famous for being an artist or a scientist?',
    'Would you rather work with animals all day or work with computers all day?',
    'Would you rather be a pilot who travels the world or an astronaut who goes to space?'
  ],
  'food fun': [
    'Would you rather eat pizza for every meal or ice cream for every meal?',
    'Would you rather give up candy for a year or give up pizza for a year?',
    'Would you rather eat food that\'s too hot or too cold?',
    'Would you rather only eat sweet foods or only eat salty foods?',
    'Would you rather cook your own meals or never have to cook again?'
  ],
  'vacations': [
    'Would you rather go to the beach or go camping in the mountains?',
    'Would you rather visit a theme park or a water park?',
    'Would you rather travel by plane or by train?',
    'Would you rather stay in a fancy hotel or camp under the stars?',
    'Would you rather visit a foreign country or explore your own country?'
  ],
  'cool technology': [
    'Would you rather have a robot that does your chores or a robot that does your homework?',
    'Would you rather live in the future with flying cars or the past with dinosaurs?',
    'Would you rather have a smartphone that never breaks or a computer that never gets slow?',
    'Would you rather be able to teleport anywhere or time travel?',
    'Would you rather invent something amazing or discover something incredible?'
  ],
  'kids tv and movies': [
    'Would you rather be in your favorite animated movie or your favorite live-action movie?',
    'Would you rather meet your favorite cartoon character or your favorite movie hero?',
    'Would you rather have superpowers like your favorite superhero or be as smart as your favorite detective?',
    'Would you rather live in the world of your favorite fantasy movie or your favorite sci-fi movie?',
    'Would you rather be the main character in a comedy or an adventure movie?'
  ]
};

export const MAD_LIBS_TEMPLATES = [
  {
    title: "The Amazing Adventure",
    template: "Once upon a time, there was a {adjective1} {noun1} who lived in a {adjective2} {place}. Every morning, the {noun1} would {verb1} to the {place2} and {verb2} with the {adjective3} {noun2}. One day, something {adjective4} happened! A {noun3} appeared and said '{exclamation}! I need your help to {verb3} the {adjective5} {noun4}!' So they {verb4} together and saved the day!",
    prompts: ["adjective1", "noun1", "adjective2", "place", "place2", "verb1", "verb2", "adjective3", "noun2", "adjective4", "noun3", "exclamation", "verb3", "adjective5", "noun4", "verb4"]
  },
  {
    title: "The Silly School Day",
    template: "Today at school was absolutely {adjective1}! In math class, our teacher Mr./Mrs. {name} asked us to {verb1} all the {noun1}. Then in science, we learned about {adjective2} {noun2} and how they {verb2}. At lunch, I ate a {adjective3} {food} sandwich and {number} {noun3}. During recess, we played {game} and I {verb3} so {adverb} that everyone said '{exclamation}!'",
    prompts: ["adjective1", "name", "verb1", "noun1", "adjective2", "noun2", "verb2", "adjective3", "food", "number", "noun3", "game", "verb3", "adverb", "exclamation"]
  },
  {
    title: "The Magic Pet",
    template: "I have the most {adjective1} pet in the whole {place}! My pet {animal} can {verb1} and {verb2} better than any other {animal} I know. Every day, we {verb3} to the {place2} and {verb4} for {number} hours. My pet's favorite food is {adjective2} {food} and its favorite toy is a {adjective3} {noun}. The most amazing thing is that my pet can {verb5} and even {verb6}! Everyone who meets my pet says '{exclamation}!'",
    prompts: ["adjective1", "place", "animal", "verb1", "verb2", "verb3", "place2", "verb4", "number", "adjective2", "food", "adjective3", "noun", "verb5", "verb6", "exclamation"]
  }
];

export const HANGMAN_PUZZLES = [
  // 1 word puzzles (8-21 letters)
  "BIRTHDAY", "SANDWICH", "ELEPHANT", "COMPUTER", "VACATION", "TREASURE", "BUTTERFLY", "CHOCOLATE",
  "ADVENTURE", "DINOSAUR", "FOOTBALL", "HOMEWORK", "KEYBOARD", "LEMONADE", "MUSHROOM", "NOTEBOOK",
  "UMBRELLA", "WATERFALL", "AIRPLANE", "BASEBALL", "CAMPFIRE", "DOORBELL", "EARPHONE", "FIREFLY",
  "GOLDFISH", "HAMBURGER", "ICECREAM", "JELLYBEAN", "KANGAROO", "LADYBUG", "MAGAZINE", "NECKLACE",
  "ORANGES", "POPCORN", "QUESTION", "RAINBOW", "STARFISH", "TOOTHBRUSH", "UNIVERSE", "VOLLEYBALL",
  "WORKSHOP", "XYLOPHONE", "YESTERDAY", "ZEPPELIN", "BACKPACK", "CUCUMBER", "DRAGONFLY", "ENVELOPE",
  "FLAMINGO", "GIRAFFE", "HEDGEHOG", "INTERNET", "JIGSAW", "KITCHEN", "LIBRARY", "MIDNIGHT",
  "NOODLES", "OCTOPUS", "PENGUIN", "QUICKSAND", "RACCOON", "SNOWMAN", "TORNADO", "UNDERDOG",
  "VOLCANO", "WINDOW", "YOGURT", "ZIPPER", "ALLIGATOR", "BUMBLEBEE", "CATERPILLAR", "DETECTIVE",
  "EMERALD", "FREEDOM", "GARBAGE", "HUMMINGBIRD", "INTERNET", "JACKPOT", "KALEIDOSCOPE", "LIZARD",
  "MOUNTAIN", "NUGGETS", "ORCHESTRA", "PASSPORT", "QUICKNESS", "RECTANGLE", "SUBMARINE", "TELESCOPE",
  "UNDERGROUND", "VEGETABLE", "WEEKEND", "EXCELLENT", "YEARBOOK", "ZOOKEEPER", "ACROBAT", "BROTHERS",
  "CARNIVAL", "DISCOVERY", "ELEPHANT", "FANTASTIC", "GYMNASIUM", "HAPPINESS", "INVISIBLE", "JELLYFISH",
  "KNOCKOUT", "LAUGHTER", "MARMALADE", "NAVIGATE", "OPERATION", "PARACHUTE", "QUOTATION", "RHYMING",
  "SANDWICH", "TOURNAMENT", "ULTIMATE", "VACATION", "WONDERFUL", "EXCITING", "YESTERDAY", "ZEPPELIN",
  
  // 2 word puzzles (8-21 letters total)
  "ICE CREAM", "HOT DOG", "SNOW DAY", "BEST PAL", "CAKE POP", "TOY BOX", "CAR WASH", "PET SHOP",
  "GAME TIME", "BIKE RIDE", "FIRE TRUCK", "SPACE SHIP", "BOOK CLUB", "FISH TANK", "TREE HOUSE",
  "MOON WALK", "SUN SHINE", "RAIN COAT", "SAND BOX", "BIRD NEST", "POOL PARTY", "CAMP FIRE",
  "FAST FOOD", "TEAM WORK", "COOL DOWN", "WARM UP", "TURN LEFT", "GO RIGHT", "STAY HOME",
  "GET READY", "HAVE FUN", "PLAY BALL", "RIDE BIKE", "LOVE LIFE", "MAKE TIME", "TAKE CARE",
  "MAIL BOX", "BUS STOP", "BANK ROLL", "CASH FLOW", "WORK HARD", "STUDY TIME", "DANCE FLOOR",
  "SING SONG", "DRAW WELL", "WRITE GOOD", "READ BOOK", "WATCH TV", "PHONE CALL", "TEXT SEND",
  "EMAIL SEND", "SURF WEB", "CLICK HERE", "SAVE FILE", "OPEN DOOR", "CLOSE LID", "TURN KEY",
  "LOCK UP", "WAKE UP", "GET UP", "SIT DOWN", "STAND UP", "WALK FAST", "RUN QUICK", "JUMP HIGH",
  "SWIM DEEP", "CLIMB TREE", "FLY KITE", "THROW BALL", "CATCH FISH", "BUILD TOY", "FIX BIKE",
  "CLEAN ROOM", "WASH CAR", "FEED PET", "WATER TREE", "PLANT SEED", "PICK FRUIT", "BAKE CAKE",
  "COOK MEAL", "MAKE SOUP", "POUR MILK", "DRINK TEA", "EAT FOOD", "TASTE GOOD", "SMELL NICE",
  "LOOK GOOD", "FEEL WELL", "SOUND FUN", "TOUCH SOFT", "THINK HARD", "DREAM BIG", "HOPE HIGH",
  "WISH WELL", "LOVE MUCH", "CARE DEEP", "HELP OUT", "GIVE BACK", "TAKE TURN", "SHARE TOY",
  "PLAY NICE", "BE KIND", "SAY HELLO", "WAVE BYE", "SMILE BIG", "LAUGH LOUD", "CRY SOFT",
  "SLEEP WELL", "REST GOOD", "RELAX NOW", "CALM DOWN", "SLOW UP", "SPEED UP", "MOVE FAST",
  
  // 3 word puzzles (8-21 letters total)
  "I LOVE YOU", "BE MY PAL", "GO TO BED", "GET UP NOW", "EAT YOUR FOOD", "WASH YOUR FACE",
  "BRUSH YOUR TEETH", "COMB YOUR HAIR", "PUT ON SHOES", "TIE YOUR LACES", "PACK YOUR BAG",
  "DO YOUR BEST", "TRY YOUR BEST", "GIVE YOUR ALL", "HAVE A BALL", "PLAY ALL DAY", "REST ALL NIGHT",
  "SLEEP ALL NIGHT", "DREAM ALL NIGHT", "WAKE UP EARLY", "GET UP LATE", "EAT ALL UP", "DRINK ALL UP",
  "USE IT ALL", "SAVE IT ALL", "KEEP IT ALL", "GIVE IT ALL", "TAKE IT ALL", "MAKE IT ALL",
  "FIX IT ALL", "DO IT ALL", "SAY IT ALL", "HEAR IT ALL", "SEE IT ALL", "FEEL IT ALL",
  "KNOW IT ALL", "LOVE IT ALL", "LIKE IT ALL", "WANT IT ALL", "NEED IT ALL", "GET IT ALL",
  "HAVE IT ALL", "BE THE BEST", "DO THE BEST", "TRY THE BEST", "GIVE THE BEST", "TAKE THE BEST",
  "MAKE THE BEST", "USE THE BEST", "KEEP THE BEST", "SAVE THE BEST", "FIND THE BEST", "PICK THE BEST",
  "CHOOSE THE BEST", "LOVE THE BEST", "LIKE THE BEST", "WANT THE BEST", "NEED THE BEST", "GET THE BEST",
  "HAVE THE BEST", "BE VERY GOOD", "DO VERY WELL", "TRY VERY HARD", "WORK VERY HARD", "PLAY VERY WELL",
  "SLEEP VERY WELL", "EAT VERY WELL", "FEEL VERY GOOD", "LOOK VERY GOOD", "SOUND VERY GOOD", "TASTE VERY GOOD",
  "SMELL VERY GOOD", "THINK VERY HARD", "DREAM VERY BIG", "HOPE VERY HIGH", "WISH VERY WELL", "LOVE VERY MUCH",
  "CARE VERY MUCH", "HELP VERY MUCH", "GIVE VERY MUCH", "TAKE VERY MUCH", "SHARE VERY MUCH", "PLAY VERY NICE",
  "BE VERY KIND", "SAY VERY NICE", "WAVE VERY HIGH", "SMILE VERY BIG", "LAUGH VERY LOUD", "CRY VERY SOFT"
];
